### ISSUE TITLE
What is this URL? What's its purpose?

### ISSUE THREAD

**Issue by jontstaz** [MiniGlome/Tiktok-uploader#15]
I was looking at the code and I see it uploads all the info to what looks like an AWS instance of some kind? Relevant code is here https://github.com/MiniGlome/Tiktok-uploader/blob/main/Tiktok_uploader.py#L87

I'm confused as to what this is. Can you explain it? I can't see any reference to it in the README and, as such, I personally would definitely remove it before I used this code.

**Comment by Wolfvaudou** [comment]
If i understand correctly, it is needed to authenticate request made to Tiktok services. Fun to think about the biggest chinese social media needing one of the biggest american  company to do that.

**Comment by MiniGlome** [comment]
Kind of funny indeed
