### ISSUE TITLE
KeyError: 'x-ware-csrf-token'

### ISSUE THREAD

**Issue by Zeffut** [MiniGlome/Tiktok-uploader#18]
Hello when i try to upload a video i've got this error can you help me ?

Traceback (most recent call last):
  File "e:\Téléchargements\Tiktok-uploader-main\Tiktok-uploader-main\main.py", line 9, in <module>
    uploadVideo(session_id, file, title, tags, verbose=True)
  File "e:\Téléchargements\Tiktok-uploader-main\Tiktok-uploader-main\Tiktok_uploader.py", line 200, in uploadVideo
    x_csrf_token = r.headers["X-Ware-Csrf-Token"].split(',')[1]
                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zeffu\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'x-ware-csrf-token'

**Comment by ComminQ** [comment]
As this [Issue](https://github.com/MiniGlome/Tiktok-uploader/issues/12#issuecomment-1687425983) says.

Remove those two lines.

After that, if you get an error likes this:

```
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"2023082711232007B7A306C2B955A9578D"},"status_code":5,"status_msg":"Invalid parameters"}'
```

You must remove the schedule_time to None. The params seems invalid. I didn't do any investigation

**Comment by Zeffut** [comment]
It works but now i got this erroe:

[-] An error occured while reaching https://www.tiktok.com/api/v1/item/create/
r = <Response [400]>
r.content = b'<HTML><HEAD>\n<TITLE>Bad Request</TITLE>\n</HEAD><BODY>\n<H1>Bad Request</H1>\nYour browser sent a request that this server could not understand.<P>\nReference&#32;&#35;7&#46;c8f71502&#46;1693141469&#46;2bd36086\n</BODY>\n</HTML>\n'

**Comment by MiniGlome** [comment]
https://github.com/MiniGlome/Tiktok-uploader/pull/17#issuecomment-1695953664
