### ISSUE TITLE
403 response

### ISSUE THREAD

**Issue by 546200350** [MiniGlome/Tiktok-uploader#3]
python3 Tiktok_uploader.py -i df81bc671227de3971387910249c4XXX -p ./download/a.mp4 -t "MY SUPER TITLE" --tags Funny Joke Fyp 
[-] An error occured while reaching https://www.tiktok.com/upload/
r = <Response [403]>
r.content = b''

**Comment by MiniGlome** [comment]
Please make sure that your session_id is valid and that you have not logged out after copying it.
Also try to reach https://www.tiktok.com/upload/ in your browser, you should be redirected to the login page if you are not logged in.

**Comment by 546200350** [comment]
i am sure that the session_id is valid. and i have not logged out yet.

**Comment by 546200350** [comment]
so,  i have find the problem.
my IP have been limited by tiktok.
i have just add ua in the header, is ok.
` headers = {
	'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'
	}
url = "https://www.tiktok.com/upload/"
r = session.get(url, headers = headers);
if not assertSuccess(url, r):
	return False
url = "https://www.tiktok.com/passport/web/account/info/"
r = session.get(url,headers=headers)
`
