### ISSUE TITLE
Invalid parameters

### ISSUE THREAD

**Issue by nhantamz** [MiniGlome/Tiktok-uploader#4]
Hi, Thank you for the script!

sometime I faced this error message, the title and tags are short and simple, no special characters. The SID is working with other videos. 
This error video is short video (27 Seconds, 5MB, food video, no sexual, porn...)

log: {"log_pb":{"impr_id":"202302020524372DF0B8EE9477F......"},"status_code":5,"status_msg":"Invalid parameters"}

Could you please help me resolve this issue?

Thank you!

**Comment by 546200350** [comment]
i have also this problem

**Comment by 546200350** [comment]
apple@sc Uploader % python3 ./index.py
[-] An error occured while reaching https://www.tiktok.com/api/v1/item/create/
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"20230202055607C189500C37F9B8006190"},"status_code":5,"status_msg":"Invalid parameters"}'

**Comment by MiniGlome** [comment]
Hello,
Can you paste the command you use?
Also, you may try to tweak these parameters line 202:
```python
params = {
  "video_id":video_id,
  "visibility_type":"0",
  "poster_delay":"0",
  "text":text,
  "text_extra":json.dumps(text_extra),
  "allow_comment":"1",   # Can be replaced to "0" to disallow comments
  "allow_duet":"0",      # Can be replaced by "1" to allow duets (Only available for videos < 1min)
  "allow_stitch":"0",    # Can be replaced by "1" to allow stitches (Only available for videos < 1min)
  "sound_exemption":"0",
  "aid":"1988",
}
```

**Comment by 546200350** [comment]
> Hello, Can you paste the command you use? Also, you may try to tweak these parameters line 202:
> 
> ```python
> params = {
>   "video_id":video_id,
>   "visibility_type":"0",
>   "poster_delay":"0",
>   "text":text,
>   "text_extra":json.dumps(text_extra),
>   "allow_comment":"1",   # Can be replaced by "0" to disallow comments
>   "allow_duet":"0",      # Can be replaced by "1" to allow duets (Only available for videos < 1min)
>   "allow_stitch":"0",    # Can be replaced by "1" to allow stitches (Only available for videos < 1min)
>   "sound_exemption":"0",
>   "aid":"1988",
> }
> ```

i have find the web api changed?
<img width="832" alt="image" src="https://user-images.githubusercontent.com/16091917/216266886-f3f3cde5-9a39-4630-95f6-9e744ad4314b.png">

**Comment by MiniGlome** [comment]
It still works on my side...
Where did you take this screenshot?

**Comment by 546200350** [comment]
it is charles.
maybe it`s the limited by Tik Tok.
sometimes it`s ok in my computer(china)  by the same code, but when i run in the server (us), it does not work

**Comment by 546200350** [comment]
and now , i have use the new api. sometimes ,it will response:
{"log_pb":{"impr_id":"20230203012156DC2725E6208EFD41F9FC"},"status_code":4,"status_msg":"Server is currently unavailable. Please try again later."}

**Comment by SushiSammy** [comment]
Also getting the same issue as above`[-] An error occured while reaching https://www.tiktok.com/api/v1/item/create/
r = <Response [200]>
r.content = b'{"log_pb":{"impr_id":"2023020608444832E51326F9486E15903C"},"status_code":5,"status_msg":"Invalid parameters"}'
`
Any updates? Trying from US

**Comment by 546200350** [comment]
finally，it has solve my problem.
just sleep for some seconds before you fetch the /item/create.

**Comment by jaredsburrows** [comment]
Did you modify the script locally?

**Comment by 546200350** [comment]
Yeah, I have request other api by tictok website.
You can try yourself.

> 2023年2月7日 10:51，Jared Burrows ***@***.***> 写道：
> 
> 
> Did you modify the script locally?
>

**Comment by nhantamz** [comment]
> 

Can you share new API link?

**Comment by 546200350** [comment]
> 

just wait amount，i share the new project

**Comment by jaredsburrows** [comment]
Any update @546200350?

Any idea @MiniGlome? :)

**Comment by 546200350** [comment]
@jaredsburrows @nhantamz 
 https://github.com/546200350/TikTokUploder

**Comment by jaredsburrows** [comment]
@546200350 Thanks! This works.
