### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by denkagood** [MiniGlome/Tiktok-uploader#6]
What could be the problem? thank you in advance)
![zzz](https://user-images.githubusercontent.com/35262925/220921137-0b2282e3-d971-48ce-be5e-a34186e86f50.PNG)

**Comment by toratalet** [comment]
There is no problem,
All requirements are already installed

**Comment by navaneeth-algorithm** [comment]
https://github.com/546200350/TikTokUploder

check this it's working perfectly
